backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "src/assets"
public_folder: "/src/assets"

collections:
  - name: "content"
    label: "Site Content"
    files:
      - name: "items"
        label: "Site Items"
        file: "src/content/items.json"
        fields:
          - label: "Site Information"
            name: "site"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
          
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - label: "Navigation"
                name: "navigation"
                widget: "list"
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
              - label: "Discord Button"
                name: "discordButton"
                widget: "object"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "Enabled", name: "enabled", widget: "boolean" }
              - label: "Login Button"
                name: "loginButton"
                widget: "object"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
          
          - label: "Game Categories"
            name: "gameCategories"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "URL", name: "url", widget: "string" }
          
          - label: "Trustpilot Reviews"
            name: "trustpilot"
            widget: "object"
            fields:
              - { label: "Left Text", name: "leftText", widget: "string" }
              - { label: "Rating Text", name: "rating", widget: "string" }
              - label: "Mobile Reviews"
                name: "mobileReviews"
                widget: "list"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
          
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Banner Image", name: "bannerImage", widget: "image" }
          
          - label: "Profile"
            name: "profile"
            widget: "object"
            fields:
              - { label: "Username", name: "username", widget: "string" }
          
          - label: "Limiteds Section"
            name: "limiteds"
            widget: "object"
            fields:
              - { label: "Section Title", name: "sectionTitle", widget: "string" }
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "ID", name: "id", widget: "string" }
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "RAP", name: "rap", widget: "string" }
                  - { label: "Price", name: "price", widget: "number" }
                  - { label: "Seller", name: "seller", widget: "string" }
          
          - label: "Modal Content"
            name: "modal"
            widget: "object"
            fields:
              - label: "Account Requirements"
                name: "accountRequirements"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - label: "Requirements"
                    name: "requirements"
                    widget: "list"
                    fields:
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Subtitle", name: "subtitle", widget: "string" }
              
              - label: "Search Step"
                name: "searchStep"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Placeholder", name: "placeholder", widget: "string" }
                  - { label: "Button Text", name: "buttonText", widget: "string" }
              
              - label: "Payment Methods"
                name: "paymentMethods"
                widget: "list"
                fields:
                  - { label: "ID", name: "id", widget: "string" }
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Symbol", name: "symbol", widget: "string" }
                  - { label: "Image", name: "image", widget: "image", required: false }
                  - label: "Images"
                    name: "images"
                    widget: "list"
                    required: false
                    field: { label: "Image", name: "image", widget: "image" }
                  - { label: "Address", name: "address", widget: "string" }
                  - { label: "QR Code", name: "qrCode", widget: "image" }
              
              - label: "Transaction Messages"
                name: "transactionMessages"
                widget: "object"
                fields:
                  - { label: "Step 2 Message", name: "step2", widget: "text" }
                  - { label: "Step 3 Warning", name: "step3Warning", widget: "text" }
                  - { label: "Step 3 Info", name: "step3Info", widget: "text" }
                  - { label: "Back Button", name: "backButton", widget: "string" }
                  - { label: "Copy Button", name: "copyButton", widget: "string" }
              
              - label: "Modal Items"
                name: "items"
                widget: "object"
                fields:
                  - label: "Playful Vampire"
                    name: "playfulVampire"
                    widget: "object"
                    fields:
                      - { label: "Name", name: "name", widget: "string" }
                      - { label: "RAP", name: "rap", widget: "string" }
                      - { label: "Buyer", name: "buyer", widget: "string" }
                      - { label: "Price", name: "price", widget: "number" }
                  - label: "Clockwork's Shades"
                    name: "clockworksShades"
                    widget: "object"
                    fields:
                      - { label: "Name", name: "name", widget: "string" }
                      - { label: "RAP", name: "rap", widget: "string" }
                      - { label: "Buyer", name: "buyer", widget: "string" }
                      - { label: "Price", name: "price", widget: "number" }
              
              - label: "Error Modal"
                name: "error"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Message", name: "message", widget: "text" }
                  - { label: "Button Text", name: "buttonText", widget: "string" }
              
              - { label: "Disclaimer", name: "disclaimer", widget: "text" }
          
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - label: "Company Information"
                name: "companyInfo"
                widget: "object"
                fields:
                  - { label: "Company Name", name: "name", widget: "string" }
                  - label: "Address"
                    name: "address"
                    widget: "list"
                    field: { label: "Address Line", name: "line", widget: "string" }
                  - { label: "Email", name: "email", widget: "string" }
              
              - label: "Links"
                name: "links"
                widget: "object"
                fields:
                  - label: "Column 1"
                    name: "column1"
                    widget: "list"
                    fields:
                      - { label: "Label", name: "label", widget: "string" }
                      - { label: "URL", name: "url", widget: "string" }
                  - label: "Column 2"
                    name: "column2"
                    widget: "list"
                    fields:
                      - { label: "Label", name: "label", widget: "string" }
                      - { label: "URL", name: "url", widget: "string" }
              
              - label: "Social"
                name: "social"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - label: "Platforms"
                    name: "platforms"
                    widget: "list"
                    field: { label: "Platform", name: "platform", widget: "string" }
              
              - { label: "Copyright", name: "copyright", widget: "string" }
              - { label: "Disclaimer", name: "disclaimer", widget: "text" }